In [1]:
import pandas as pd
import numpy as np
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)


games = pd.read_csv('games.csv')
players = pd.read_csv('players.csv')
plays = pd.read_csv('plays.csv')
# tackels = pd.read_csv('tackles.csv')
first_week = pd.read_csv('tracking_week_1.csv')

In [2]:
first_week

             gameId  playId    nflId     displayName  frameId                        time  jerseyNumber      club playDirection          x      y     s     a   dis       o     dir         event
0        2022090800      56  35472.0  Rodger Saffold        1  2022-09-08 20:24:05.200000          76.0       BUF          left  88.370000  27.27  1.62  1.15  0.16  231.74  147.90           NaN
1        2022090800      56  35472.0  Rodger Saffold        2  2022-09-08 20:24:05.299999          76.0       BUF          left  88.470000  27.13  1.67  0.61  0.17  230.98  148.53  pass_arrived
2        2022090800      56  35472.0  Rodger Saffold        3  2022-09-08 20:24:05.400000          76.0       BUF          left  88.560000  27.01  1.57  0.49  0.15  230.98  147.05           NaN
3        2022090800      56  35472.0  Rodger Saffold        4  2022-09-08 20:24:05.500000          76.0       BUF          left  88.640000  26.90  1.44  0.89  0.14  232.38  145.42           NaN
4        2022090800      56  35472.0  Rodger Saffold        5  2022-09-08 20:24:05.599999          76.0       BUF          left  88.720000  26.80  1.29  1.24  0.13  233.36  141.95           NaN
...             ...     ...      ...             ...      ...                         ...           ...       ...           ...        ...    ...   ...   ...   ...     ...     ...           ...
1407434  2022091200    3826      NaN        football       49  2022-09-12 23:05:57.799999           NaN  football          left  56.220001   9.89  2.56  1.25  0.25     NaN     NaN        tackle
1407435  2022091200    3826      NaN        football       50  2022-09-12 23:05:57.900000           NaN  football          left  56.060001  10.08  2.50  1.14  0.24     NaN     NaN           NaN
1407436  2022091200    3826      NaN        football       51  2022-09-12 23:05:58.000000           NaN  football          left  55.889999  10.27  2.38  1.70  0.25     NaN     NaN           NaN
1407437  2022091200    3826      NaN        football       52  2022-09-12 23:05:58.099999           NaN  football          left  55.730000  10.44  2.07  2.83  0.24     NaN     NaN           NaN
1407438  2022091200    3826      NaN        football       53  2022-09-12 23:05:58.200000           NaN  football          left  55.570000  10.57  1.86  3.00  0.20     NaN     NaN           NaN

[1407439 rows x 17 columns]